//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cold_Water
    {
        public int ID { get; set; }
        public int CW1 { get; set; }
        public int CW0 { get; set; }
        public int CWT { get; set; }
        public int CWP { get; set; }
        public int CWD { get; set; }
        public decimal Sum { get; set; }
        public int HomID { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
