//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electricity
    {
        public int ID { get; set; }
        public int EC { get; set; }
        public int EP { get; set; }
        public int ED { get; set; }
        public int L150_250 { get; set; }
        public int upL150_250 { get; set; }
        public decimal Sum { get; set; }
        public int HomID { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
