//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hom
    {
        public Hom()
        {
            this.Cold_Water = new HashSet<Cold_Water>();
            this.Hot_Water = new HashSet<Hot_Water>();
            this.Electricity = new HashSet<Electricity>();
            this.Tarrif = new HashSet<Tarrif>();
            this.Sewage = new HashSet<Sewage>();
        }
    
        public int ID { get; set; }
        public int Apartament_naber { get; set; }
        public bool Benefit { get; set; }
        public bool Gas { get; set; }
    
        public virtual ICollection<Cold_Water> Cold_Water { get; set; }
        public virtual ICollection<Hot_Water> Hot_Water { get; set; }
        public virtual ICollection<Electricity> Electricity { get; set; }
        public virtual ICollection<Tarrif> Tarrif { get; set; }
        public virtual ICollection<Sewage> Sewage { get; set; }
    }
}
