//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hot_Water
    {
        public int ID { get; set; }
        public int HW1 { get; set; }
        public int HW0 { get; set; }
        public int HWT { get; set; }
        public int HWP { get; set; }
        public int HWD { get; set; }
        public decimal Sum { get; set; }
        public int HomID { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
