//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefit
    {
        public int ID { get; set; }
        public short Privilege { get; set; }
        public short Persons { get; set; }
        public decimal E { get; set; }
        public decimal CW { get; set; }
        public decimal HW { get; set; }
        public decimal S { get; set; }
        public int HomID { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
