//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cold_Water
    {
        public int ID { get; set; }
        public int CW1 { get; set; }
        public int CW0 { get; set; }
        public int CWT { get; set; }
        public int CWP { get; set; }
        public int CWD { get; set; }
        public decimal Sum { get; set; }
        public int HomID { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
