//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Electricity
    {
        public int ID { get; set; }
        public int EC { get; set; }
        public int EP { get; set; }
        public int ED { get; set; }
        public int Privelege { get; set; }
        public int toLim { get; set; }
        public int fromLim { get; set; }
        public Nullable<int> overLim { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal SumP { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal SumT { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal SumF { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal Sum { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public Nullable<decimal> SumO { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Data { get; set; }
        public int HomID { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
