//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electricity
    {
        public int ID { get; set; }
        public int EC { get; set; }
        public int EP { get; set; }
        public int ED { get; set; }
        public int Privelege { get; set; }
        public int toLim { get; set; }
        public int fromLim { get; set; }
        public Nullable<int> overLim { get; set; }
        public decimal SumP { get; set; }
        public decimal SumT { get; set; }
        public decimal SumF { get; set; }
        public decimal Sum { get; set; }
        public Nullable<decimal> SumO { get; set; }
        public System.DateTime Data { get; set; }
        public int HomID { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
