//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gas
    {
        public int ID { get; set; }
        public int GC { get; set; }
        public int GP { get; set; }
        public int GD { get; set; }
        public Nullable<int> Privelege { get; set; }
        public decimal Sum { get; set; }
        public System.DateTime Data { get; set; }
        public int HomID { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
