//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Gas
    {
        public int ID { get; set; }
        public int GC { get; set; }
        public int GP { get; set; }
        public int GD { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public Nullable<int> Privelege { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal Sum { get; set; }
        public System.DateTime Data { get; set; }
        public int HomID { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
