//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hom
    {
        public Hom()
        {
            this.Cold_Water = new HashSet<Cold_Water>();
            this.Hot_Water = new HashSet<Hot_Water>();
            this.Electricity = new HashSet<Electricity>();
            this.Tarrif = new HashSet<Tarrif>();
            this.Sewage = new HashSet<Sewage>();
            this.Benefit1 = new HashSet<Benefit>();
            this.Gas1 = new HashSet<Gas>();
            this.Limits = new HashSet<Limits>();
        }
    
        public int ID { get; set; }
        public int Apartament_naber { get; set; }
        public bool Benefit { get; set; }
        public bool Gas { get; set; }
    
        public virtual ICollection<Cold_Water> Cold_Water { get; set; }
        public virtual ICollection<Hot_Water> Hot_Water { get; set; }
        public virtual ICollection<Electricity> Electricity { get; set; }
        public virtual ICollection<Tarrif> Tarrif { get; set; }
        public virtual ICollection<Sewage> Sewage { get; set; }
        public virtual ICollection<Benefit> Benefit1 { get; set; }
        public virtual ICollection<Gas> Gas1 { get; set; }
        public virtual ICollection<Limits> Limits { get; set; }
    }
}
