//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hot_Water
    {
        public int ID { get; set; }
        public int HW1 { get; set; }
        public int HW0 { get; set; }
        public int HWT { get; set; }
        public int HWP { get; set; }
        public int HWD { get; set; }
        public decimal Sum { get; set; }
        public int HomID { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
