//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limits
    {
        public int ID { get; set; }
        public int E_L1 { get; set; }
        public int E_L2 { get; set; }
        public int E_L3 { get; set; }
        public int HomID { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
