//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Hom> HomItems { get; set; }
        public DbSet<Cold_Water> Cold_WaterНабор { get; set; }
        public DbSet<Hot_Water> Hot_WaterНабор { get; set; }
        public DbSet<Electricity> ElectricityНабор { get; set; }
        public DbSet<Tarrif> TarrifНабор { get; set; }
        public DbSet<Sewage> SewageНабор { get; set; }
        public DbSet<Benefit> Benefit { get; set; }
        public DbSet<Gas> GasНабор { get; set; }
        public DbSet<Limits> LimitsНабор { get; set; }
    }
}
