//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sewage
    {
        public int ID { get; set; }
        public int S1 { get; set; }
        public int S0 { get; set; }
        public int ST { get; set; }
        public int SP { get; set; }
        public int SD { get; set; }
        public decimal Sum { get; set; }
        public System.DateTime Data { get; set; }
        public int HomID { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
