//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarrif
    {
        public int ID { get; set; }
        public decimal CW { get; set; }
        public decimal HW { get; set; }
        public decimal S { get; set; }
        public decimal E_T { get; set; }
        public decimal E_F { get; set; }
        public Nullable<decimal> E_O { get; set; }
        public int HomID { get; set; }
        public decimal Gas { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
