//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHOME
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tarrif
    {
        public int ID { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal CW { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal HW { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal S { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal E_T { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal E_F { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public Nullable<decimal> E_O { get; set; }
        public int HomID { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0000}")]
        public decimal Gas { get; set; }
    
        public virtual Hom Hom { get; set; }
    }
}
